const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { test } = require('node:test');
const ts = require('../node_modules/typescript');
const root = path.resolve(__dirname, '../components/landing-preview');
const cache = new Map();
function load(name) {
  if (cache.has(name)) return cache.get(name);
  if (name.endsWith('.json')) return JSON.parse(fs.readFileSync(path.join(root, name), 'utf8'));
  const filename = path.join(root, `${name}.ts`);
  const module = { exports: {} };
  const code = ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } }).outputText;
  vm.runInNewContext(code, { module, exports: module.exports, require: load, structuredClone }, { filename });
  cache.set(name, module.exports);
  return module.exports;
}
const { initialState, demoReducer, queueEmbed, trackEmbed } = load('./demo-state');
const command = (state, value) => demoReducer(state, { type: 'command', value, random: .72 });
test('resolved tracks share player, queue, seek capability and reorder state', () => {
  const track = { title: 'Real result', artist: 'Artist', duration: '4:00', cover: '', uri: 'https://youtu.be/example', seekable: false };
  let state = command(initialState(), '/pause');
  state = demoReducer(state, { type: 'resolved', tracks: [track] });
  assert.equal(state.paused, true); assert.equal(state.queue.length, 3);
  state = demoReducer(state, { type: 'move', from: 2, to: 0 }); assert.equal(state.queue[0].title, track.title);
  state = command(state, '/skip'); assert.equal(state.current.title, track.title);
  state = command(state, '/seek 1:00'); assert.equal(state.position, 0);
  state = demoReducer(state, { type: 'remove', index: 0 }); assert.equal(state.queue.length, 1);
  state = demoReducer(state, { type: 'resolved', tracks: [track], mode: 'now' }); assert.equal(state.position, 0);
  const copy = initialState(); assert.equal(copy.queue.length, 2);
});
test('play queues without restarting or unpausing; historical queue replies stay snapshots', () => {
  let state = command(initialState(), '/pause');
  state = command(state, '/queue');
  const snapshot = state.messages.at(-1).snapshot;
  state = command(state, '/play Kendrick Lamar');
  assert.equal(state.paused, true); assert.equal(state.position, 84); assert.equal(state.queue.length, 3);
  assert.equal(snapshot.queue.length, 2);
  assert.match(state.messages.at(-1).embed.title, /Added to queue/);
});
test('volume and seek validate, clamp and update the embed', () => {
  let state = command(initialState(), '/volume 0');
  assert.equal(state.volume, 0);
  state = command(state, '/volume 1000'); assert.equal(state.volume, 100);
  state = command(state, '/volume nope'); assert.equal(state.volume, 100);
  state = command(state, '/seek 2:10'); assert.equal(state.position, 130);
  state = command(state, '/seek 9:00'); assert.equal(state.position, 130);
  const embed = trackEmbed('nowPlaying', state.current, state);
  assert.match(embed.description, /2:10 \/ 5:37/);
  assert.equal(embed.fields[2].value, '100%');
});
test('Activity seek retains millisecond precision and rejects invalid or unseekable tracks', () => {
  const initial = initialState();
  let state = demoReducer(initial, { type: 'seek', position: 12.345 });
  assert.equal(state.position, 12.345);
  state = demoReducer(state, { type: 'seek', position: NaN });
  assert.equal(state.position, 12.345);
  state = demoReducer(state, { type: 'seek', position: -5 });
  assert.equal(state.position, 0);
  state = demoReducer(state, { type: 'seek', position: 999 });
  assert.equal(state.position, 336.999);
  const live = { ...initial, current: { ...initial.current, seekable: false } };
  assert.equal(demoReducer(live, { type: 'seek', position: 10 }).position, initial.position);
  const stopped = command(initial, '/stop');
  assert.equal(demoReducer(stopped, { type: 'seek', position: 10 }).position, 0);
});

test('natural end repeats a track but manual skip advances; back restores previous', () => {
  let state = command(initialState(), '/loop track');
  state = demoReducer({ ...state, position: 336 }, { type: 'tick' });
  assert.equal(state.position, 0); assert.equal(state.current.title, 'Instant Crush');
  state = command(state, '/skip'); assert.equal(state.current.title, 'Not Like Us');
  state = command(state, '/back'); assert.equal(state.current.title, 'Instant Crush');
  assert.equal(state.queue[0].title, 'Not Like Us');
});
test('queue loop, stop/disconnect and play from empty', () => {
  let state = command(initialState(), '/loop queue');
  state = command(state, '/skip'); assert.equal(state.queue.at(-1).title, 'Instant Crush');
  state = command(state, '/stop'); assert.equal(state.current, null); assert.equal(state.queue.length, 0);
  state = command(state, '/queue'); assert.equal(state.messages.at(-1).text, 'The queue is empty.');
  state = command(state, '/play Quebonafide'); assert.equal(state.current.title, 'BUBBLETEA');
  assert.equal(state.position, 0); assert.equal(state.paused, false);
});
test('pagination, bounded history and unsupported query feedback', () => {
  let state = initialState();
  for (let i = 0; i < 45; i++) state = command(state, '/play Kendrick Lamar');
  assert.equal(state.messages.length, 40);
  assert.match(queueEmbed(state, 1).footer.text, /Page 2\/5/);
  assert.match(queueEmbed(state, 1).description, /`11\.`/);
  const length = state.queue.length;
  state = command(state, '/play unknown'); assert.equal(state.queue.length, length);
  assert.match(state.messages.at(-1).text, /No match/);
  state = command(state, '/slots 100'); assert.match(state.messages.at(-1).text, /without a bet/);
});
test('autoplay picks a track when the queue runs out and shows it as up next', () => {
  const { autoplayNext } = load('./demo-state');
  let state = command(initialState(), '/autoplay toggle');
  assert.equal(state.autoplay, true); assert.equal(state.messages.at(-1).embed.title, 'Autoplay Enabled');
  state = command(command(state, '/skip'), '/skip');
  assert.equal(state.current.title, 'BUBBLETEA'); assert.equal(state.queue.length, 0);
  const upNext = autoplayNext(state);
  const embed = trackEmbed('nowPlaying', state.current, state, { upNext });
  assert.equal(embed.title, 'Now Playing [AUTO]');
  assert.match(embed.fields.at(-1).value, new RegExp(upNext.title));
  state = command(state, '/autoplay next');
  assert.match(state.messages.at(-1).text, /Up next/); assert.notEqual(autoplayNext(state).title, upNext.title);
  const picked = autoplayNext(state);
  state = command(state, '/skip');
  assert.equal(state.current.title, picked.title); assert.equal(state.current.autoplay, true);
  assert.equal(trackEmbed('nowPlaying', state.current, state).footer.text, 'Picked by autoplay');
  assert.equal(command(initialState(), '/autoplay next').messages.at(-1).text, 'Autoplay is off.');
});
test('dislike skips and is avoided by autoplay; artist block and disliked panel', () => {
  const { autoplayNext } = load('./demo-state');
  let state = command(initialState(), '/autoplay like');
  assert.match(state.messages.at(-1).text, /Liked \*\*Instant Crush\*\*/);
  state = command(state, '/autoplay dislike');
  assert.equal(state.current.title, 'Not Like Us'); assert.match(state.messages.at(-1).text, /Disliked \*\*Instant Crush\*\*/);
  state = command(state, '/autoplay dislike artist');
  assert.match(state.messages.at(-1).text, /Blocked \*\*Kendrick Lamar\*\*/);
  for (let cursor = 0; cursor < 6; cursor++) assert.ok(!['Instant Crush', 'Not Like Us'].includes(autoplayNext({ ...state, current: null, autoplayCursor: cursor }).title));
  state = command(state, '/autoplay disliked');
  assert.match(state.messages.at(-1).embed.description, /Blocked artists[\s\S]*Kendrick Lamar[\s\S]*Disliked tracks[\s\S]*Instant Crush/);
  assert.match(command(initialState(), '/autoplay disliked').messages.at(-1).embed.description, /Nothing here/);
  assert.match(command(initialState(), '/autoplay bogus').messages.at(-1).text, /toggle, like, dislike/);
});
test('radio plays a live station that cannot be seeked, liked or looped', () => {
  let state = command(initialState(), '/radio Midnight Jazz');
  assert.equal(state.current.live, true); assert.equal(state.current.title, 'Midnight Jazz');
  assert.equal(state.messages.at(-2).embed.title, '📻 Live radio'); assert.equal(state.messages.at(-2).stationId, 'jazz');
  assert.equal(state.previous.at(-1).title, 'Instant Crush');
  const embed = trackEmbed('nowPlaying', state.current, state, { upNext: null });
  assert.match(embed.description, /LIVE/); assert.ok(!embed.fields.some(field => field.name === '📻 Up next'));
  const ticked = demoReducer(state, { type: 'tick' }); assert.equal(ticked.position, 0);
  assert.match(command(state, '/seek 1:00').messages.at(-1).text, /cannot be seeked/);
  assert.match(command(state, '/autoplay like').messages.at(-1).text, /cannot be liked/);
  state = command(state, '/radio');
  assert.equal(state.messages.at(-2).embed.title, '📻 Switched station'); assert.equal(state.current.title, 'Synthwave City');
  assert.equal(state.previous.at(-1).title, 'Instant Crush');
  assert.match(command(state, '/radio nowhere fm').messages.at(-1).text, /No station matched/);
  state = demoReducer(state, { type: 'saveStation', id: 'jazz' });
  assert.equal(state.savedStations.join(), 'jazz'); assert.match(state.messages.at(-1).text, /Saved \*\*Midnight Jazz\*\*/);
  state = demoReducer(state, { type: 'saveStation', id: 'jazz' });
  assert.equal(state.savedStations.length, 0);
});
test('sound presets and stats views validate their option', () => {
  const { soundEmbed } = load('./demo-state');
  let state = command(initialState(), '/sound nightcore');
  assert.equal(state.preset, 'nightcore'); assert.equal(state.soundId, state.messages.at(-1).id);
  assert.match(soundEmbed(state.preset).description, /Nightcore/);
  state = demoReducer(state, { type: 'preset', preset: 'bassboost' }); assert.equal(state.preset, 'bassboost');
  assert.equal(demoReducer(state, { type: 'preset', preset: 'loud' }).preset, 'bassboost');
  assert.match(command(state, '/sound loud').messages.at(-1).text, /Choose a preset/);
  state = command(state, '/stats');
  assert.equal(state.messages.at(-1).kind, 'stats'); assert.equal(state.messages.at(-1).view, 'overview');
  assert.equal(command(state, '/stats view: rhythm').messages.at(-1).view, 'rhythm');
  assert.match(command(state, '/stats weather').messages.at(-1).text, /Choose a view/);
});
